//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Marca { get; set; }
        public string Unidad_Medida { get; set; }
        public Nullable<int> Existencia { get; set; }
        public Nullable<double> Precio_Unitario { get; set; }
        public Nullable<double> Precio_Venta { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
    }
}
