//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia_Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        [Required(ErrorMessage ="Apellido Paterno Requerido")]
        [Display(Name ="Apellido Paterno")]
        public string APaterno { get; set; }        
        [Display(Name = "Apellido Materno")]
        public string AMaterno { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }

        [Display(Name ="Creado el")]
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        [Display(Name = "Modificado el")]
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
