//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_DETALLE
    {
        public int Id { get; set; }
        public Nullable<int> Id_Pedido { get; set; }
        public Nullable<int> Id_Articulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Monto { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
