//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha_Pedido { get; set; }
        public int Id_Cliente { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
