//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_DETALLE
    {
        public int Id { get; set; }
        public Nullable<int> Id_Pedido { get; set; }
        public Nullable<int> Id_Articulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Monto { get; set; }
    }
}
